// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 da1sh1n
// This file is part of Romzeta, licensed under the GNU General Public License
// v3.0 or later. Romzeta comes with ABSOLUTELY NO WARRANTY. See the LICENSE file
// or <https://www.gnu.org/licenses/> for details.

//! Bakes the trusted public keys into `listener.exe`.
//!
//! # Why this is a build script and not a config file
//!
//! The listener's job is to decide whether to run a program off a disk someone
//! just plugged in. The signature makes that decision unforgeable — but only as
//! far as the list of keys it checks against is itself trustworthy. If that list
//! were a line in `config.toml` beside the exe, anything able to write that file
//! could append its own key and get arbitrary code auto-run on every insert. An
//! attacker would not forge a signature; they would skip straight past the need
//! for one. The trust anchor has to be at least as hard to change as the check
//! it feeds, so it is compiled in, and changing it means replacing the binary.
//!
//! # The two keys
//!
//! `keys/romzeta.pub` is the release key and is committed. `keys/dev.pub` is
//! whatever `cargo run -p xtask -- keygen` generated on this machine, and is
//! gitignored. A listener trusts both, which is what makes a clone of this repo
//! usable: your build accepts your cartridges *and* official ones, while an
//! official listener still refuses yours.
//!
//! Either may be absent — a fresh clone has no dev key, and this repo has not
//! cut a release yet — but **not both**, because a listener that trusts nothing
//! would refuse every cartridge in existence and log its way through the
//! confusion one volume at a time. That is a build error with an instruction
//! attached, not a runtime surprise.

use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").expect("set by cargo"));
    let keys = manifest
        .parent()
        .expect("listener/ has a parent")
        .join("keys");
    let out = PathBuf::from(std::env::var_os("OUT_DIR").expect("set by cargo"));

    let mut anchors = Vec::new();
    for (name, file) in [("release", "romzeta.pub"), ("dev", "dev.pub")] {
        let path = keys.join(file);
        // Rebuild when a key appears, changes or is deleted — including the
        // "appears" case, which is what happens right after `xtask keygen`.
        println!("cargo::rerun-if-changed={}", path.display());

        let Ok(text) = fs::read_to_string(&path) else {
            continue;
        };
        match base64_line(&text) {
            Some(key) => anchors.push((name, key)),
            None => println!(
                "cargo::warning={} exists but holds no key line; ignoring it",
                path.display()
            ),
        }
    }

    if anchors.is_empty() {
        println!(
            "cargo::error=no trusted public key: neither {} nor {} exists.",
            keys.join("romzeta.pub").display(),
            keys.join("dev.pub").display()
        );
        println!(
            "cargo::error=a listener with no trust anchor would refuse every cartridge. \
             Generate a signing key with `cargo run -p xtask -- keygen`."
        );
        return;
    }

    let mut rust = String::from(
        "// Generated by build.rs. The public keys this binary trusts, in the\n\
         // order it tries them. Not configurable at runtime, by design.\n\
         pub const ANCHORS: &[Anchor] = &[\n",
    );
    for (name, key) in &anchors {
        rust.push_str(&format!(
            "    Anchor {{ name: {name:?}, base64: {key:?} }},\n"
        ));
    }
    rust.push_str("];\n");

    fs::write(out.join("trust_anchors.rs"), rust).expect("write trust_anchors.rs");

    embed_resources();
}

/// Compiles `assets/listener.ico` and a version block into the exe.
///
/// The icon is what `LoadIconW` in `trigger/windows.rs` pulls the tray icon
/// from, and the version block's `FileDescription` is what Task Manager shows
/// instead of the bare filename — both come from the same resource, built
/// once here rather than requiring a `.rc` file of our own.
#[cfg(windows)]
fn embed_resources() {
    let mut res = winres::WindowsResource::new();
    res.set_icon("assets/listener.ico");
    res.set("FileDescription", "Romzeta Listener");
    res.set("ProductName", "Romzeta");
    res.compile()
        .expect("compile Windows resources (icon, version info)");
}

#[cfg(not(windows))]
fn embed_resources() {}

/// Pulls the key out of a minisign `.pub` file.
///
/// The format is a comment line then the key, but the comment is free text a
/// human may well have edited, so this takes the last line that is neither
/// blank nor a comment rather than trusting the line count. Kept in step with
/// `xtask/src/keys.rs::base64_line`, which reads the very same files.
fn base64_line(text: &str) -> Option<String> {
    text.lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with("untrusted comment:"))
        .next_back()
        .map(str::to_string)
}
